### ISSUE TITLE
Jobs started from OSX Chia UI are causing plotman to fail

### ISSUE THREAD

**Issue by Nopik** [ericaltendorf/plotman#158]
When I have jobs running in Chia UI on MacOS, `plotman` throws this (on `@development` branch):
```
Traceback (most recent call last):
  File "/usr/local/bin/plotman", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/plotman/plotman.py", line 160, in main
    jobs = Job.get_running_jobs(cfg.directories.log)
  File "/usr/local/lib/python3.9/site-packages/plotman/job.py", line 94, in get_running_jobs
    job = Job(proc, logroot)
  File "/usr/local/lib/python3.9/site-packages/plotman/job.py", line 117, in __init__
    val = None if arg in {'-e', '--nobitfield', '-h', '--help', '--override-k'} else next(args_iter)
StopIteration
```
When I printed out `args[3:]`, it was:
```
['-k32', '-n1', '-t/Volumes/hdd0/tmp', '-2/Volumes/hdd0/tmp2', '-d/Volumes/hdd0/final', '-b3390', '-u128', '-r4', '-a1873810580']
```
So, as a dirty hack I tried adding `-a1873810580` to  https://github.com/ericaltendorf/plotman/blob/main/src/plotman/job.py#L115 and to https://github.com/ericaltendorf/plotman/blob/main/src/plotman/job.py#L134 and caused plotman to start working fine, jobs started to be recognized.

**Comment by altendky** [comment]
As discussed on Keybase, https://github.com/ericaltendorf/plotman/pull/116 hopefully helps.  Follow up whenever you get a chance to try it out (again, and hopefully unbroken).  Thanks.

**Comment by aaroneden** [comment]
I'm getting this same error on Ubuntu.  Please let me know if there are additional details I can provide to help with hunting this one down.

**Comment by altendky** [comment]
@aaroneden did you try the branch in https://github.com/ericaltendorf/plotman/pull/116?  You can install it by using `git+https://github.com/altendky/plotman@use_chia_cli_parser`. in place of the url in the [readme instructions](https://github.com/ericaltendorf/plotman#installation).

**Comment by aaroneden** [comment]
Sorry, I meant to post this morning and got busy with work.  YES!  This fixed the issue for me, thank you!

Aaron Eden | 520-360-7193

**Comment by altendky** [comment]
@aaroneden, thanks.  Hopefully I can make the adjustments I want soon and get that merged.

**Comment by BasilHorowt** [comment]
Looks like the linked PR (https://github.com/ericaltendorf/plotman/pull/116) is still not in main, but this issue can be closed once it is
