### ISSUE TITLE
Issue: AttributeError: 'NoneType' object has no attribute 'rsyncd_user'

### ISSUE THREAD

**Issue by petrzmax** [ericaltendorf/plotman#175]
Hi!
I'm struggling at managing plotman to work. Even with activated environment I'm getting this kind of error:

```python-traceback
Traceback (most recent call last):
  File "/home/petrzmax/chia-blockchain/venv/bin/plotman", line 8, in <module>
    sys.exit(main())
  File "/home/petrzmax/chia-blockchain/venv/lib/python3.9/site-packages/plotman/plotman.py", line 168, in main
    print(reporting.dirs_report(jobs, cfg.directories, cfg.scheduling, get_term_width()))
  File "/home/petrzmax/chia-blockchain/venv/lib/python3.9/site-packages/plotman/reporting.py", line 193, in dirs_report
    arch_dir_report(archive.get_archdir_freebytes(dir_cfg.archive), width) + '\n'
  File "/home/petrzmax/chia-blockchain/venv/lib/python3.9/site-packages/plotman/archive.py", line 53, in get_archdir_freebytes
    (arch_cfg.rsyncd_user, arch_cfg.rsyncd_host, arch_cfg.rsyncd_path) )
AttributeError: 'NoneType' object has no attribute 'rsyncd_user'
```

Do You have any ideas how to fix it?

**Comment by altendky** [comment]
I think this was fixed in https://github.com/ericaltendorf/plotman/pull/138.  I just merged it so it is available on the development branch if you want to try it out.

**Comment by petrzmax** [comment]
Thank You!  I can confirm - it's fixed on dev branch.
