### ISSUE TITLE
Plotman ont react of any commands like status dir etc... 

### ISSUE THREAD

**Issue by schleichit** [ericaltendorf/plotman#213]
`plotman dirs`
```python-traceback
Traceback (most recent call last):
  File "/home/troon/chia-blockchain/venv/bin/plotman", line 8, in <module>
    sys.exit(main())
  File "/home/troon/chia-blockchain/venv/lib/python3.7/site-packages/plotman/plotman.py", line 135, in main
    cfg = configuration.get_validated_configs()
  File "/home/troon/chia-blockchain/venv/lib/python3.7/site-packages/plotman/configuration.py", line 28, in get_validated_configs
    config_file = yaml.load(file, Loader=yaml.SafeLoader)
  File "/home/troon/chia-blockchain/venv/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/home/troon/chia-blockchain/venv/lib/python3.7/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/home/troon/chia-blockchain/venv/lib/python3.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/troon/chia-blockchain/venv/lib/python3.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/home/troon/chia-blockchain/venv/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/troon/chia-blockchain/venv/lib/python3.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/troon/chia-blockchain/venv/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/troon/chia-blockchain/venv/lib/python3.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/troon/chia-blockchain/venv/lib/python3.7/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/home/troon/chia-blockchain/venv/lib/python3.7/site-packages/yaml/composer.py", line 110, in compose_sequence_node
    while not self.check_event(SequenceEndEvent):
  File "/home/troon/chia-blockchain/venv/lib/python3.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/home/troon/chia-blockchain/venv/lib/python3.7/site-packages/yaml/parser.py", line 382, in parse_block_sequence_entry
    if self.check_token(BlockEntryToken):
  File "/home/troon/chia-blockchain/venv/lib/python3.7/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/home/troon/chia-blockchain/venv/lib/python3.7/site-packages/yaml/scanner.py", line 260, in fetch_more_tokens
    self.get_mark())
yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "/home/troon/.config/plotman/plotman.yaml", line 32, column 1
```

**Comment by schleichit** [comment]
Changed config severey times and same issue always. Whats wrong? somebody same Issue or Solution ?

**Comment by altendky** [comment]
You have a tab in your configuration and there shouldn't be any tabs, only spaces.  pasting your config into https://bpa.st/+yaml may help highlight the issue area if the line number in the error is not sufficient.  There are probably also other sites that are explicitly for solving errors in yaml.

**Comment by BasilHorowt** [comment]
@schleichit I'm going to close this because it is a YAML parsing issue, hopefully you have solved it in the last week :)
