### ISSUE TITLE
plotman fails if you have a plot going outside the plotman context

### ISSUE THREAD

**Issue by drewmullen** [ericaltendorf/plotman#215]
```
$ chia plots create -k 32 -n 4 -b 4000 -r 4 -t /chia-plot0 -d /chia-buffer
$ pip install --force-reinstall git+https://github.com/ericaltendorf/plotman@development
$ plotman status
 plot id    k            tmp                        dst    wall   phase   tmp     pid   stat      mem    user    sys     io
--------   32    /chia-plot1   /mnt/synology/usbshare1/   22:22     ?:?     0   11921    SLP     4.9G   21:47   1:02   4:50
^ one is already running outside plotman context

$ plotman plot
Traceback (most recent call last):
  File "/home/farmer3/chia-blockchain/venv/bin/plotman", line 8, in <module>
    sys.exit(main())
  File "/home/farmer3/chia-blockchain/venv/lib/python3.7/site-packages/plotman/plotman.py", line 143, in main
    wait_reason = manager.maybe_start_new_plot(cfg.directories, cfg.scheduling, cfg.plotting)
  File "/home/farmer3/chia-blockchain/venv/lib/python3.7/site-packages/plotman/manager.py", line 92, in maybe_start_new_plot
    tmpdir = max(rankable, key=operator.itemgetter(1))[0]
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

in reference to: https://github.com/ericaltendorf/plotman/issues/199#issuecomment-830660078

**Comment by fnando** [comment]
The following workaround fixed my issue in `main`:

```diff
94,96c94,100
<                         job = Job(proc, logroot)
<                         if not job.help:
<                             jobs.append(job)
---
>                         try:
>                             job = Job(proc, logroot)
>                             if not job.help:
>                                 jobs.append(job)
>                         except Exception as e:
>                             # print("Error:", e)
>                             pass
100c104
<  
---
> 
```

Ideally, plotman would also read logfiles from `~/.chia/plotter`, but I don't know if that's feasible.

**Comment by altendky** [comment]
I am interested in adjusting how log files are identified.  This may involve configuring multiple log directories to check or possibly other means of detection.  Though, this issue is for when we still don't find a log file it seems.  Remember that creating a log file is a purely optional thing.  There's no guarantee that `chia plots create` output is directed to a file.

Anyways, I made an attempt at a fix in #258.  I haven't run it yet but if you want to give it a try, let me know how it goes.
