### ISSUE TITLE
plotman kill not working

### ISSUE THREAD

**Issue by kxknet** [ericaltendorf/plotman#236]
I use newest version chia and latest developer version plotman
See this
plotman kill 2c3e4235
Namespace(cmd='kill', idprefix=['2c3e4235'])
Pausing PID 4195, plot id 2c3e4235e0cf36fcfeb167b7da60f4310a6a47a6c4545011a8573d2120041d83
Traceback (most recent call last):
  File "/chia-blockchain/venv/bin/plotman", line 8, in <module>
    sys.exit(main())
  File "/chia-blockchain/venv/lib/python3.8/site-packages/plotman/plotman.py", line 230, in main
    temp_files = job.get_temp_files()
  File "/chia-blockchain/venv/lib/python3.8/site-packages/plotman/job.py", line 373, in get_temp_files
    if self.tmpdir in f.path or self.tmp2dir in f.path or self.dstdir in f.path:
TypeError: 'in <string>' requires string as left operand, not NoneType

**Comment by JordyBaylac** [comment]
@kxknet it was happening to me as well, I  have submitted a PR

**Comment by braveckin** [comment]
It "works" for me in the way that it suspends the job instead of killing it and removing the temp files as it states in the message... I was even able to resume the job...
