### ISSUE TITLE
the reporting console has error

### ISSUE THREAD

**Issue by jjhesk** [ericaltendorf/plotman#243]
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ipant/.local/lib/python3.8/site-packages/plotmanx/__main__.py", line 10, in <module>
    plotman.main()
  File "/home/ipant/.local/lib/python3.8/site-packages/plotmanx/plotman.py", line 197, in main
    interactive.run_interactive()
  File "/home/ipant/.local/lib/python3.8/site-packages/plotmanx/interactive.py", line 367, in run_interactive
    curses.wrapper(curses_main)
  File "/usr/lib/python3.8/curses/__init__.py", line 105, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/ipant/.local/lib/python3.8/site-packages/plotmanx/interactive.py", line 275, in curses_main
    jobs_win.addstr(0, 0, reporting.status_report(jobs, n_cols, jobs_h,
  File "/home/ipant/.local/lib/python3.8/site-packages/plotmanx/reporting.py", line 142, in status_report
    tab.add_row(row)
  File "/home/ipant/.local/lib/python3.8/site-packages/texttable.py", line 375, in add_row
    self._check_row_size(array)
  File "/home/ipant/.local/lib/python3.8/site-packages/texttable.py", line 526, in _check_row_size
    raise ArraySizeError("array should contain %d elements" \
texttable.ArraySizeError: array should contain 16 elements

when i start using the full item chart

**Comment by XerrorYT** [comment]
Try maximising the terminal window and re-running the command.
Solved the problem for me.

**Comment by jjhesk** [comment]
nope. that error is from the display column.. I resolved that finally.
