### ISSUE TITLE
Can't comment achive section

### ISSUE THREAD

**Issue by hrtplt** [ericaltendorf/plotman#247]
after comment archive: section i get an error:
```
(venv) user@plot1:~/chia-blockchain$ plotman dirs
Traceback (most recent call last):
  File "/home/user/chia-blockchain/venv/bin/plotman", line 8, in <module>
    sys.exit(main())
  File "/home/user/chia-blockchain/venv/lib/python3.8/site-packages/plotman/plotman.py", line 168, in main
    print(reporting.dirs_report(jobs, cfg.directories, cfg.scheduling, get_term_width()))
  File "/home/user/chia-blockchain/venv/lib/python3.8/site-packages/plotman/reporting.py", line 193, in dirs_report
    arch_dir_report(archive.get_archdir_freebytes(dir_cfg.archive), width) + '\n'
  File "/home/user/chia-blockchain/venv/lib/python3.8/site-packages/plotman/archive.py", line 53, in get_archdir_freebytes
    (arch_cfg.rsyncd_user, arch_cfg.rsyncd_host, arch_cfg.rsyncd_path) )
AttributeError: 'NoneType' object has no attribute 'rsyncd_user'
```

**Comment by ericaltendorf** [comment]
are you on `main` or `development` branch?

did you comment out only the lines inside the archive section, or did you also comment out the line that defines the archiving group of the config?

**Comment by hrtplt** [comment]
I have attached a file, just cleaned keys and changed to txt
[plotman.txt](https://github.com/ericaltendorf/plotman/files/6435882/plotman.txt)

**Comment by altendky** [comment]
It looks like this should have been fixed awhile ago.  ​Including in 0.2 on main.

https://github.com/ericaltendorf/plotman/commit/5acc58ebb153000b46f56e8c5da4d2948f7b6175#diff-ffeb7e10ab32bfe64115f768f591072b294160dbfed69c6d6c3a008d9d046669R93-R94

If you are still having an issue, could you please share an updated traceback from `development`?

**Comment by solkirans** [comment]
Having same issue. Archive topic is not commented out but the parameters are commented out. When I try to run plotman dirs command, I get 

AttributeError: 'NoneType' object has no attribute 'rsyncd_user'

**Comment by BasilHorowt** [comment]
@solkirans if you don't want archiving then you should comment out the root "archive:" group as well.  I don't believe it is designed for you to comment out only the items within the group.

**Comment by hrtplt** [comment]
> It looks like this should have been fixed awhile ago. ​Including in 0.2 on main.
> 
> [5acc58e#diff-ffeb7e10ab32bfe64115f768f591072b294160dbfed69c6d6c3a008d9d046669R93-R94](https://github.com/ericaltendorf/plotman/commit/5acc58ebb153000b46f56e8c5da4d2948f7b6175#diff-ffeb7e10ab32bfe64115f768f591072b294160dbfed69c6d6c3a008d9d046669R93-R94)
> 
> If you are still having an issue, could you please share an updated traceback from `development`?

`development` works fine, thx
