### ISSUE TITLE
can't run plotman plot in ubunut20.04

### ISSUE THREAD

**Issue by liuxiangqaz** [ericaltendorf/plotman#249]
(venv) root@linnx8600k:/home/qazxiang/chia-blockchain# plotman plot
Traceback (most recent call last):
  File "/home/qazxiang/chia-blockchain/venv/bin/plotman", line 8, in <module>
    sys.exit(main())
  File "/home/qazxiang/chia-blockchain/venv/lib/python3.8/site-packages/plotman/plotman.py", line 135, in main
    cfg = configuration.get_validated_configs()
  File "/home/qazxiang/chia-blockchain/venv/lib/python3.8/site-packages/plotman/configuration.py", line 28, in get_validated_configs
    config_file = yaml.load(file, Loader=yaml.SafeLoader)
  File "/home/qazxiang/chia-blockchain/venv/lib/python3.8/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/home/qazxiang/chia-blockchain/venv/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/home/qazxiang/chia-blockchain/venv/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/qazxiang/chia-blockchain/venv/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/home/qazxiang/chia-blockchain/venv/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/qazxiang/chia-blockchain/venv/lib/python3.8/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/qazxiang/chia-blockchain/venv/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/qazxiang/chia-blockchain/venv/lib/python3.8/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/home/qazxiang/chia-blockchain/venv/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/home/qazxiang/chia-blockchain/venv/lib/python3.8/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
  in "/root/.config/plotman/plotman.yaml", line 111, column 9
expected <block end>, but found '<block mapping start>'
  in "/root/.config/plotman/plotman.yaml", line 117, column 12
(venv) root@linnx8600k:/home/qazxiang/chia-blockchain# chia plotman plot
Usage: chia [OPTIONS] COMMAND [ARGS]...
![image](https://user-images.githubusercontent.com/30262839/117256640-8296d480-ae7d-11eb-967d-0f3175b8890d.png)

**Comment by ericaltendorf** [comment]
sounds like you have a malformatted config.  make sure you've understood
how YAML files are parsed and check the format of your config?

**Comment by liuxiangqaz** [comment]
![image](https://user-images.githubusercontent.com/30262839/117260334-8f1d2c00-ae81-11eb-9e2f-2c9f1ad4e8c7.png)

**Comment by liuxiangqaz** [comment]
![image](https://user-images.githubusercontent.com/30262839/117260689-e9b68800-ae81-11eb-91cc-6966d101861d.png)

**Comment by liuxiangqaz** [comment]
![image](https://user-images.githubusercontent.com/30262839/117260949-2c786000-ae82-11eb-8d74-3adf50b457d6.png)
![image](https://user-images.githubusercontent.com/30262839/117261010-3e5a0300-ae82-11eb-87ba-761bb84409e9.png)
![image](https://user-images.githubusercontent.com/30262839/117261125-5d589500-ae82-11eb-8b36-576a75ada2a2.png)

**Comment by liuxiangqaz** [comment]
![image](https://user-images.githubusercontent.com/30262839/117288341-f8ab3380-ae9d-11eb-92ac-b86affdfd876.png)
check plotman.yaml  is normal, run plotman plot,return:

![image](https://user-images.githubusercontent.com/30262839/117289285-ff867600-ae9e-11eb-953a-f427781c52e5.png)

**Comment by liuxiangqaz** [comment]
Did I run it successfully?
![Uploading image.png…]()

**Comment by jjhesk** [comment]
this version is too old..

**Comment by asukahan** [comment]
> > this version is too old.
> 
> who old version? plotman or chia ?

哥们你的who用的真牛比
