### ISSUE TITLE
m1 Mac mini error

### ISSUE THREAD

**Issue by vvashkot** [ericaltendorf/plotman#275]
followed all the instructions to the T, when trying to run "plotman interactive" this is what I get.  Tried on other m1 macs in my house, same issue.

```
Mac-mini:~ dit-mini-3$ plotman interactive
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/plotman", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/plotman/plotman.py", line 171, in main
    interactive.run_interactive()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/plotman/interactive.py", line 353, in run_interactive
    curses.wrapper(curses_main)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/plotman/interactive.py", line 112, in curses_main
    (started, msg) = manager.maybe_start_new_plot(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/plotman/manager.py", line 130, in maybe_start_new_plot
    p = subprocess.Popen(plot_args,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'chia'

```

**Comment by BasilHorowt** [comment]
@vvashkot I'm running no problem on a M1 Mac Mini 16gb (getting 20 or 21 plots per day with an external NVME).  I believe your issue is that you are not running `plotman interactive` from within the chia venv, so do `. ./activate` first and then `plotman interactive`.  If you still have trouble you can come chat on keybase : keybase://chat/chia_network.public#plotman

**Comment by BasilHorowt** [comment]
@vvashkot I'm going to close this as I am confidant it is not an m1 issue, please let me know on keybase if it isn't working for you

**Comment by vvashkot** [comment]
> @vvashkot I'm going to close this as I am confidant it is not an m1 issue, please let me know on keybase if it isn't working for you

can't get keybase to work unfortunately, channels just hang indefinitely.  I can get plotman to work but it just keeps starting processes and eventually crashes the interactive. I've tried specifying different .yaml concurrent processes but nothing seems to work unfortunately.
