### ISSUE TITLE
job.py throws when there is now temp2 is specified and trying to kill a process

### ISSUE THREAD

**Issue by nbayaman** [ericaltendorf/plotman#276]
` plotman kill 2f01
Namespace(cmd='kill', idprefix=['2f01'])
Pausing PID 6186, plot id 2f01113f17bf5c7222026ec8bb5cc7d762d2c55c8085f36a5e68a9ba4510b905
Traceback (most recent call last):
  File "/home/nurlan/chia/venv/bin/plotman", line 8, in <module>
    sys.exit(main())
  File "/home/nurlan/chia/venv/lib/python3.8/site-packages/plotman/plotman.py", line 230, in main
    temp_files = job.get_temp_files()
  File "/home/nurlan/chia/venv/lib/python3.8/site-packages/plotman/job.py", line 373, in get_temp_files
    if self.tmpdir in f.path or self.tmp2dir in f.path or self.dstdir in f.path:
TypeError: 'in <string>' requires string as left operand, not NoneType`

`if self.tmpdir in f.path or self.tmp2dir in f.path or self.dstdir in f.path:
` 
self.tmp2dir should be sanitized here I guess

**Comment by altendky** [comment]
I swear I fixed something like this in the past week...  but I can't find it.  Anyways, easy enough.  Thanks for the report.
