### ISSUE TITLE
Install Plotman w/ Chia's Experimental GUI Installer

### ISSUE THREAD

**Issue by ijf4ghub313** [ericaltendorf/plotman#301]
Linux Mint 20.04
I installed Chia via the "experimental GUI installer" (_chia-blockchain_1.1.5_amd64.deb_) and because it doesn't quite operate the same ---no requirement to . ./activate the virtual environment, etc--- I'm not sure if I'm performing the Plotman install correctly (actually I'm pretty sure I'm not). 

Any insight on the differences of installing Plotman if I used Chia's "experimental GUI installer"? 
( The Chia GUI does seem to be operating fine ... I'm synced and generating plots like mad. )

But I'm not even sure where Chia installed to ... looks like it might be in `/usr/lib/chia-blockchain` directory(?), but . ./activate doesnt work from there and when I try to install Plotman i get a 'launchpadlib' error and a "`WARNING: The script plotman is installed in '/home/ijf/.local/bin' which is not on PATH.`" during install. And nothing seems to work after install either ... "`plotman: command not found`".

I think if I could just get over this hump your instructions are very followable.

**Comment by bradsquicciarini** [comment]
If you installed it with the experimental GUI installer, it won't work. It can't find active jobs. I have an open pull request to allow it to work with the experimental GUI install. 

But as for your install problems, you just need to sym link it.

```
# Find the location of plotman
pip show plotman

# Use the path from that output to sym link it to something in your $PATH
ln -s <path to plotman> /usr/local/bin/plotman
```

**Comment by altendky** [comment]
Did you try the development branch?  There are various fixes related to not-Python installs of chia.

**Comment by ijf313-github** [comment]
Thanks for the help guys. I think I'll just wait for a future version. I'm new enough with Linux, Chia, and GitHub that I'll just be wasting your time asking noob questions. Looking forward to using Plotman in the future. Thanks for the work you're doing. -ijf

**Comment by altendky** [comment]
FWIW, installing the development version of plotman involves following the regular installation instructions and using `@development` rather than `@main`.  But sure, I might get a release out tonight, maybe.

**Comment by lexzz** [comment]
Hey! I'm having the same question.

Tried to install the development version but seeing "plotman: command not found" 
As described I made a symlink but maybe forgot something? Hope you can give me a hint.

Thanks in advance!

**Comment by lexzz** [comment]
@ijf313-github Thanks for your message

After some trying I was able to install Plotman with pip3 but still wasn't able to get it going.
I'm going to give it another try and otherwise I keep watching the new releases and the issues you mentioned.

If I find a solution I will let you know ;)

**Comment by josinaldobarbosa** [comment]
```
WARNING: The script plotman is installed in '/home/josinaldo/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
```

pip3 show plotman
```
Name: plotman
Version: 0.2
Summary: Chia plotting manager
Home-page: https://github.com/ericaltendorf/plotman
Author: Eric Altendorf
Author-email: None
License: Apache 2.0
Location: /home/josinaldo/.local/lib/python3.8/site-packages
Requires: click, marshmallow, pendulum, desert, attrs, psutil, pyyaml, texttable, appdirs
Required-by:
```
sudo ln -s /home/josinaldo/.local/lib/python3.8/site-packages /usr/local/bin/plotman
$ plotman version
plotman: command not found

@bradsquicciarini  what am I doing wrong?

**Comment by altendky** [comment]
If you could try out https://github.com/ericaltendorf/plotman/pull/418, that'd be great.  Follow the regular readme installation but use `git+https://github.com/altendky/plotman@skip_matching_plot_process_parents` as the url.

**Comment by maxbelz** [comment]
> If you could try out #418, that'd be great. Follow the regular readme installation but use `git+https://github.com/altendky/plotman@skip_matching_plot_process_parents` as the url.

no repository with this name @skip_matching_plot_process_parents

**Comment by maxbelz** [comment]
ok i see i see it is merged with development branch

**Comment by defaultsecurity** [comment]
I'm having the same problem. I installed chia using the experimental installer.
$ plotman version = **plotman 0.3.1+dev**

> Traceback (most recent call last):
>   File "/home/username/.local/bin/plotman", line 8, in <module>
>     sys.exit(main())
>   File "/home/username/.local/lib/python3.9/site-packages/plotman/plotman.py", line 179, in main
>     interactive.run_interactive()
>   File "/home/username/.local/lib/python3.9/site-packages/plotman/interactive.py", line 335, in run_interactive
>     curses.wrapper(curses_main)
>   File "/usr/lib/python3.9/curses/__init__.py", line 94, in wrapper
>     return func(stdscr, *args, **kwds)
>   File "/home/username/.local/lib/python3.9/site-packages/plotman/interactive.py", line 117, in curses_main
>     (started, msg) = manager.maybe_start_new_plot(
>   File "/home/username/.local/lib/python3.9/site-packages/plotman/manager.py", line 169, in maybe_start_new_plot
>     p = subprocess.Popen(plot_args,
>   File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: 'chia'

**Comment by maxbelz** [comment]
so looks like there is no way to use plotman with gui,right? i need this gui just for farm and monitoring farming processes etc.. already installed gui, if i know , i wouldn't...

**Comment by ijf313-github** [comment]
I used Chia 1.1.6 as a chance to remove the experimental [Chia] installer and re-install via command line per their instructions. Previously I had trouble getting through the installation without errors (what drove me to use the experimental installer) but this time I breezed through without issue (not sure of the reason). Then I ran the Plotman installer again following the exact instructions provided on the Code page. Installation went smooth. Plotman is working great. I'm only a day in, but its sooooo much nicer than trying to handle plotting by hand or with the Chia GUI. Phew!
