### ISSUE TITLE
Seems it doesn't work properly on centos 8.3

### ISSUE THREAD

**Issue by sayarasin** [ericaltendorf/plotman#308]
OS: centos 8.3
chia version 1.1.5

I installed plotman by:
cd chia root directory
source ./activate
pip install --force-reinstall git+https://github.com/ericaltendorf/plotman@main
when it finished, I run 'plotman config generate' or 'plotman -h', but received:

Traceback (most recent call last):
  File "/root/chia-blockchain/venv/bin/plotman", line 5, in <module>
    from plotman.plotman import main
  File "/root/chia-blockchain/venv/lib/python3.7/site-packages/plotman/plotman.py", line 10, in <module>
    from plotman import analyzer, archive, configuration, interactive, manager, plot_util, reporting
  File "/root/chia-blockchain/venv/lib/python3.7/site-packages/plotman/interactive.py", line 1, in <module>
    import curses
  File "/usr/local/lib/python3.7/curses/__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'

I think maybe I lost curses module, but I checked:
pip list | grep curse
curses-2048            1.4
curses-menu            0.5.0
curses-util            0.0.25

and linux rpm 
rpm -qa | grep curses
ncurses-libs-6.1-7.20180224.el8.x86_64
ncurses-6.1-7.20180224.el8.x86_64
ncurses-base-6.1-7.20180224.el8.noarch
ncurses-devel-6.1-7.20180224.el8.x86_64
ncurses-c++-libs-6.1-7.20180224.el8.x86_64

is all done.

I have no idea why it doesn't work :(

**Comment by danarbraz** [comment]
See my comment here- https://github.com/ericaltendorf/plotman/issues/195#issuecomment-832703024. I believe that also installs the correct curses package.

**Comment by sayarasin** [comment]
> See my comment here- [#195 (comment)](https://github.com/ericaltendorf/plotman/issues/195#issuecomment-832703024). I believe that also installs the correct curses package.

Bro, thanks for your help, it works.
This is the process that I resolve this problem, maybe this could help someone who use centos8+

dnf install readline readline-devel ncurses-devel

cd Python3.7.7 (where your source code of python3.7.7 stored)
./configure --enable-optimizations; sudo make -j$(nproc) altinstall; cd ..

then you can enter your chia-blockchain directory and  activate chia environment, use 'plotman config generate' to generate the plotman configure file.

good luck!
