### ISSUE TITLE
plotman plot not working

### ISSUE THREAD

**Issue by agustinmono** [ericaltendorf/plotman#320]
Hi im having this problem
![image](https://user-images.githubusercontent.com/50418223/117718714-d0c81280-b1b2-11eb-9d16-ea6e3750a2aa.png)

...starting plot loop
```python-traceback
Traceback (most recent call last):
  File "/home/sidekick/chia-blockchain/venv/bin/plotman", line 8, in <module>
    sys.exit(main())
  File "/home/sidekick/chia-blockchain/venv/lib/python3.8/site-packages/plotman/plotman.py", line 143, in main
    wait_reason = manager.maybe_start_new_plot(cfg.directories, cfg.scheduling, cfg.plotting)
  File "/home/sidekick/chia-blockchain/venv/lib/python3.8/site-packages/plotman/manager.py", line 131, in maybe_start_new_plot
    stdout=open(logfile, 'w'),
FileNotFoundError: [Errno 2] No such file or directory: '~/chiaPlotman/logs/2021-05-10-17:11:03.log'
```

![image](https://user-images.githubusercontent.com/50418223/117718814-fbb26680-b1b2-11eb-8a08-f8fbd8d84b8b.png)

**Comment by piotrkochan** [comment]
```
mkdir -p ~/chiaPlotman/logs/
```

**Comment by PopsJon** [comment]
I'm also having this same issue. The directory exists and I tried granting all access to create/delete files.. still not working.

**Comment by piotrkochan** [comment]
> I'm also having this same issue. The directory exists and I tried granting all access to create/delete files.. still not working.

"not working". Funny sentence. There is probably error on the screen you should share.
