### ISSUE TITLE
new install, plotmans dirs fails with tuple error

### ISSUE THREAD

**Issue by syadnom** [ericaltendorf/plotman#386]
**Describe the bug**
fresh install version 0.3 
#plotman version
plotman 0.3

Can run plotman due to error:
AttributeError: 'tuple' object has no attribute 'known'

generated stock config and created directories listed there, ie ZERO changes to config file.
Also tried my own config file, identical error.  Went to the stock config to take my own errors out of the mix.

**To Reproduce**
fresh chia install
source to chia
install plotman via instructions
create config
try to execute anything.

 - OS: ubuntu 20.04 server

**Config**
the stock one generated

#plotman dirs
```python-traceback
Traceback (most recent call last):
  File "/home/dan/chia-blockchain/venv/bin/plotman", line 8, in <module>
    sys.exit(main())
  File "/home/dan/chia-blockchain/venv/lib/python3.8/site-packages/plotman/plotman.py", line 170, in main
    print(reporting.dirs_report(jobs, cfg.directories, cfg.scheduling, get_term_width()))
  File "/home/dan/chia-blockchain/venv/lib/python3.8/site-packages/plotman/reporting.py", line 193, in dirs_report
    dst_dir_report(jobs, dir_cfg.dst, width),
  File "/home/dan/chia-blockchain/venv/lib/python3.8/site-packages/plotman/reporting.py", line 165, in dst_dir_report
    priority = archive.compute_priority(eldest_ph, gb_free, n_plots)
  File "/home/dan/chia-blockchain/venv/lib/python3.8/site-packages/plotman/archive.py", line 65, in compute_priority
    if (phase.known):
AttributeError: 'tuple' object has no attribute 'known'
```

**Comment by altendky** [comment]
Thanks for the report.  That was fixed a few hours ago.  Hopefully the hotfix will be released soon.  You can jump ahead and try installing with `@release/v0.3.1` instead of `@main` if you want.

**Comment by syadnom** [comment]
ok, that got it running, but now it's not respecting the scheduling.  I have it all set to 1 so I should only get 1 plot per temp:

scheduling:
        tmpdir_stagger_phase_major: 1
        tmpdir_stagger_phase_minor: 1
        tmpdir_stagger_phase_limit: 1
        tmpdir_max_jobs: 1
        global_max_jobs: 9
        global_stagger_m: 1
        polling_time_s: 20

        tmp:
                - /chia/sdj1/temp
                - /chia/sdk1/temp
                - /chia/sdl1/temp
                - /chia/sdn1/temp
                - /chia/sdv1/temp
                - /chia/sdu1/temp
                - /chia/sdt1/temp
                - /chia/sds1/temp
                - /chia/sdr1/temp



Instead all jobs are landing in the first temp folder
05-13 01:02:34 Starting plot job: chia plots create -k 32 -r 4 -u 128 -b 3400 -t /chia/sdj1/temp -d /chia/sdr1/plot2 -f 928225a04fc2f821949421a137a319c8383e5a8dc3d8c6374c0d4cbe11ae7b8490a1458564645c9cbf567963a3abdd39 -p b33f26a344d1f2b2c6fc127c5d3669fad9
05-13 01:02:55 Starting plot job: chia plots create -k 32 -r 4 -u 128 -b 3400 -t /chia/sdj1/temp -d /chia/sdr1/plot2 -f 928225a04fc2f821949421a137a319c8383e5a8dc3d8c6374c0d4cbe11ae7b8490a1458564645c9cbf567963a3abdd39 -p b33f26a344d1f2b2c6fc127c5d3669fad9
05-13 01:03:15 Starting plot job: chia plots create -k 32 -r 4 -u 128 -b 3400 -t /chia/sdj1/temp -d /chia/sds1/plot1 -f 928225a04fc2f821949421a137a319c8383e5a8dc3d8c6374c0d4cbe11ae7b8490a1458564645c9cbf567963a3abdd39 -p b33f26a344d1f2b2c6fc127c5d3669fad9
05-13 01:03:35 Starting plot job: chia plots create -k 32 -r 4 -u 128 -b 3400 -t /chia/sdj1/temp -d /chia/sds1/plot2 -f 928225a04fc2f821949421a137a319c8383e5a8dc3d8c6374c0d4cbe11ae7b8490a1458564645c9cbf567963a3abdd39 -p b33f26a344d1f2b2c6fc127c5d3669fad9
05-13 01:03:55 Starting plot job: chia plots create -k 32 -r 4 -u 128 -b 3400 -t /chia/sdj1/temp -d /chia/sdr1/plot3 -f 928225a04fc2f821949421a137a319c8383e5a8dc3d8c6374c0d4cbe11ae7b8490a1458564645c9cbf567963a3abdd39 -p b33f26a344d1f2b2c6fc127c5d3669fad9
05-13 01:04:15 Starting plot job: chia plots create -k 32 -r 4 -u 128 -b 3400 -t /chia/sdj1/temp -d /chia/sdr1/plot1 -f 928225a04fc2f821949421a137a319c8383e5a8dc3d8c6374c0d4cbe11ae7b8490a1458564645c9cbf567963a3abdd39 -p b33f26a344d1f2b2c6fc127c5d3669fad9
05-13 01:04:36 Starting plot job: chia plots create -k 32 -r 4 -u 128 -b 3400 -t /chia/sdj1/temp -d /chia/sds1/plot1 -f 928225a04fc2f821949421a137a319c8383e5a8dc3d8c6374c0d4cbe11ae7b8490a1458564645c9cbf567963a3abdd39 -p b33f26a344d1f2b2c6fc127c5d3669fad9

**Comment by syadnom** [comment]
scratch that, it's failing.  chia logs
Traceback (most recent call last):
  File "/home/dan/chia-blockchain/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/dan/chia-blockchain/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/dan/chia-blockchain/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (click 8.0.0 (/home/dan/chia-blockchain/venv/lib/python3.8/site-packages), Requirement.parse('click==7.1.2'), {'chia-blockchain'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dan/chia-blockchain/venv/bin/chia", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia')())
  File "/home/dan/chia-blockchain/venv/bin/chia", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/dan/chia-blockchain/chia/__init__.py", line 1, in <module>
    from pkg_resources import DistributionNotFound, get_distribution, resource_filename
  File "/home/dan/chia-blockchain/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "/home/dan/chia-blockchain/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/home/dan/chia-blockchain/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/dan/chia-blockchain/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/dan/chia-blockchain/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/dan/chia-blockchain/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'click==7.1.2' distribution was not found and is required by chia-blockchain

**Comment by syadnom** [comment]
all is well with the update.  I did have a python issue on this machine but I resolved that.  ignore the previous comments, I've deleted them.

**Comment by altendky** [comment]
@syadnom thanks for testing it out and sorry for the hassle.
