### ISSUE TITLE
If current //plots -d are NOT in config.yaml, I see an error

### ISSUE THREAD

**Issue by toastygunn** [ericaltendorf/plotman#46]
@ericaltendorf I found two more issues I wanted to see if you or someone else confirmed as my second two HDDs were filled today. I was busy getting my farmer 100% ready for mainnet (including evicting some small HDDs back into USB cases and into a milkcrate) but
My use model is that as I fill a USB HDD, I remove it from plotman's config.yaml, add the new one, and then restart plotman interactive. The idea is that that plotman will just pickup and send new plots to the new drive(s) instead of the old one.

I can live with removing the drive when its full and temporarily creating a symlink to the new drive so the old plots complete but then I ran into problem #2

1) If there are // plots currently in progress BUT I don't have the -d defined in the plotman config.yaml, I get this error.
Traceback (most recent call last):
  File "./plotman.py", line 123, in <module>
    interactive.run_interactive()
  File "/chia/plotman/interactive.py", line 312, in run_interactive
    curses.wrapper(curses_main)
  File "/usr/lib/python3.8/curses/__init__.py", line 105, in wrapper
    return func(stdscr, *args, **kwds)
  File "/chia/plotman/interactive.py", line 207, in curses_main
    jobs_win.addstr(0, 0, reporting.status_report(jobs, n_cols, jobs_height, 
_curses.error: addwstr() returned ERR

Yeah, this is not sustainable.  I can keep things going continuously by just creating symlinks from the old targets to the new target BUT its not clean. I guess on my next reboot (when I take down ALL my //plots), I'll configure plotman to target 1-2 symlinks called output1 and output2. I will then symlink those to my destiantion drives until plotman can detect that dst drives are full.

I will then avoid messing with plotman's folders entirely but its kind of a hack.

**Comment by toastygunn** [comment]
As eric mentioned on keybase, I think the issue was based on the size of the terminal window instead of something specific to the code looking for the old -d based on //plots currently in progress.
