### ISSUE TITLE
Issue running plotman

### ISSUE THREAD

**Issue by ArminAghayan** [ericaltendorf/plotman#489]
Traceback (most recent call last):
  File "/home/miner1/chia-blockchain/venv/bin/plotman", line 8, in <module>
    sys.exit(main())
  File "/home/miner1/chia-blockchain/venv/lib/python3.8/site-packages/plotman/plotman.py", line 137, in main
    cfg = configuration.get_validated_configs(config_text, config_path)
  File "/home/miner1/chia-blockchain/venv/lib/python3.8/site-packages/plotman/configuration.py", line 37, in get_validated_configs
    config_objects = yaml.load(config_text, Loader=yaml.SafeLoader)
  File "/home/miner1/chia-blockchain/venv/lib/python3.8/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/home/miner1/chia-blockchain/venv/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/home/miner1/chia-blockchain/venv/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/miner1/chia-blockchain/venv/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/home/miner1/chia-blockchain/venv/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/miner1/chia-blockchain/venv/lib/python3.8/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/home/miner1/chia-blockchain/venv/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/home/miner1/chia-blockchain/venv/lib/python3.8/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
  in "<unicode string>", line 5, column 1:
    user_interface:
    ^
expected <block end>, but found '-'
  in "<unicode string>", line 29, column 1:
    - /mnt/ssd1
    ^

**Comment by ceecko** [comment]
Your config seems to be incorrect. Check the line 29 in your config and make sure the spaces are correct.
You can validate your config here http://www.yamllint.com/

**Comment by ArminAghayan** [comment]
(<unknown>): did not find expected key while parsing a block mapping at line 34 column 9 

# Plotting scheduling parameters
scheduling:
        # Run a job on a particular temp dir only if the number of existing jobs
        # before [tmpdir_stagger_phase_major : tmpdir_stagger_phase_minor]
        # is less than tmpdir_stagger_phase_limit.
        # Phase major corresponds to the plot phase, phase minor corresponds to
        # the table or table pair in sequence, phase limit corresponds to
        # the number of plots allowed before [phase major : phase minor].
        # e.g, with default settings, a new plot will start only when your plot
        # reaches phase [2 : 1] on your temp drive. This setting takes precidence
        # over global_stagger_m
        tmpdir_stagger_phase_major: 1
        tmpdir_stagger_phase_minor: 1
        # Optional: default is 1
        tmpdir_stagger_phase_limit: 1

        # Don't run more than this many jobs at a time on a single temp dir.
        tmpdir_max_jobs: 7

        # Don't run more than this many jobs at a time in total.
        global_max_jobs: 7

        # Don't run any jobs (across all temp dirs) more often than this, in minutes.
        global_stagger_m: 90

        # How often the daemon wakes to consider starting a new plot job, in seconds.
        polling_time_s: 20


# Plotting parameters.  These are pass-through parameters to chia plots create.
# See documentation at
# https://github.com/Chia-Network/chia-blockchain/wiki/CLI-Commands-Reference#create
plotting:
        k: 32
        e: False             # Use -e plotting option
        n_threads: 4         # Threads per job
        n_buckets: 128       # Number of buckets to split data into
        job_buffer: 3400     # Per job memory
        # If specified, pass through to the -f and -p options.  See CLI reference.

**Comment by ArminAghayan** [comment]
Traceback (most recent call last):
  File "/home/chia1/chia-blockchain/venv/bin/plotman", line 8, in <module>
    sys.exit(main())
  File "/home/chia1/chia-blockchain/venv/lib/python3.8/site-packages/plotman/plotman.py", line 137, in main
    cfg = configuration.get_validated_configs(config_text, config_path)
  File "/home/chia1/chia-blockchain/venv/lib/python3.8/site-packages/plotman/configuration.py", line 37, in get_validated_configs
    config_objects = yaml.load(config_text, Loader=yaml.SafeLoader)
  File "/home/chia1/chia-blockchain/venv/lib/python3.8/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/home/chia1/chia-blockchain/venv/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/home/chia1/chia-blockchain/venv/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/chia1/chia-blockchain/venv/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/home/chia1/chia-blockchain/venv/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/chia1/chia-blockchain/venv/lib/python3.8/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/chia1/chia-blockchain/venv/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/chia1/chia-blockchain/venv/lib/python3.8/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/home/chia1/chia-blockchain/venv/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/home/chia1/chia-blockchain/venv/lib/python3.8/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/home/chia1/chia-blockchain/venv/lib/python3.8/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/home/chia1/chia-blockchain/venv/lib/python3.8/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "/home/chia1/chia-blockchain/venv/lib/python3.8/site-packages/yaml/scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "<unicode string>", line 131, column 10:
            e: False             # Use -e plo ...

**Comment by ArminAghayan** [comment]
Traceback (most recent call last):
  File "/home/chia1/chia-blockchain/venv/bin/plotman", line 8, in <module>
    sys.exit(main())
  File "/home/chia1/chia-blockchain/venv/lib/python3.8/site-packages/plotman/plotman.py", line 137, in main
    cfg = configuration.get_validated_configs(config_text, config_path)
  File "/home/chia1/chia-blockchain/venv/lib/python3.8/site-packages/plotman/configuration.py", line 37, in get_validated_configs
    config_objects = yaml.load(config_text, Loader=yaml.SafeLoader)
  File "/home/chia1/chia-blockchain/venv/lib/python3.8/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/home/chia1/chia-blockchain/venv/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/home/chia1/chia-blockchain/venv/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/chia1/chia-blockchain/venv/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/home/chia1/chia-blockchain/venv/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/chia1/chia-blockchain/venv/lib/python3.8/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/chia1/chia-blockchain/venv/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/chia1/chia-blockchain/venv/lib/python3.8/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/home/chia1/chia-blockchain/venv/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/home/chia1/chia-blockchain/venv/lib/python3.8/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/home/chia1/chia-blockchain/venv/lib/python3.8/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/home/chia1/chia-blockchain/venv/lib/python3.8/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "/home/chia1/chia-blockchain/venv/lib/python3.8/site-packages/yaml/scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "<unicode string>", line 131, column 10:
            e: False             # Use -e plo ...

**Comment by ArminAghayan** [comment]
syntax issue thank for the link!
