### ISSUE TITLE
Plotman interactive throws tuple error

### ISSUE THREAD

**Issue by charterhouse-services** [ericaltendorf/plotman#505]
**Describe the bug**
plotman interactive throws tuple error

Steps to reproduce the behavior, e.g.:
1. Setup and run successfully plotman plots
2. Run pip install --force-reinstall git+https://github.com/ericaltendorf/plotman@main - top ensure latest and greatest is installed
3. Run plotman interactove
(venv) john@plotter:~/chia-blockchain$ plotman interactive
Traceback (most recent call last):
  File "/home/john/.local/bin/plotman", line 8, in <module>
    sys.exit(main())
  File "/home/john/.local/lib/python3.8/site-packages/plotman/plotman.py", line 173, in main
    interactive.run_interactive()
  File "/home/john/.local/lib/python3.8/site-packages/plotman/interactive.py", line 334, in run_interactive
    curses.wrapper(curses_main)
  File "/usr/lib/python3.8/curses/__init__.py", line 105, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/john/.local/lib/python3.8/site-packages/plotman/interactive.py", line 180, in curses_main
    dst_report = reporting.dst_dir_report(
  File "/home/john/.local/lib/python3.8/site-packages/plotman/reporting.py", line 165, in dst_dir_report
    priority = archive.compute_priority(eldest_ph, gb_free, n_plots)
  File "/home/john/.local/lib/python3.8/site-packages/plotman/archive.py", line 65, in compute_priority
    if (phase.known):
AttributeError: 'tuple' object has no attribute 'known'
(venv) john@plotter:~/chia-blockchain$

**Expected behavior**
I cannot comment because to be honest this is my first time using Plotman

**System setup:**
 - OS: Ubuntu 20.04 - Linux plotter 5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

 - Method of archiving (e.g., none, rsyncd, rsync, ...)
NONE (But manually scripted)

**Config**
# Options for display and rendering
user_interface:
        use_stty_size: True

# Where to plot and log.
directories:
        log: /var/log/chia_logs
        tmp:
                - /home/john/mnt/plotting
        tmp_overrides:
                "/home/john/mnt/plotting":
                        tmpdir_max_jobs: 20

        dst:
                - /home/john/mnt/transit1
                - /home/john/mnt/transit2

scheduling:
        tmpdir_stagger_phase_major: 1 #default 2
        tmpdir_stagger_phase_minor: 5 #default 1

        # Optional: default is 1
        tmpdir_stagger_phase_limit: 5 #default 1

        # Don't run more than this many jobs at a time on a single temp dir.
        tmpdir_max_jobs: 12

        # Don't run more than this many jobs at a time in total.
        global_max_jobs: 15

        # Don't run any jobs (across all temp dirs) more often than this, in minutes.
        global_stagger_m: 30

        # How often the daemon wakes to consider starting a new plot job, in seconds.
        polling_time_s: 20

plotting:
        k: 32
        e: False             # Use -e plotting option
        n_threads: 4         # Threads per job
        n_buckets: 128       # Number of buckets to split data into
        job_buffer: 3390     # Per job memory

**Comment by ebeng** [comment]
how did you install Chia? 
I just did a new installation of Chia, today on Ubuntu server 20.04: 0 errors....

Check if you can write in the "/home/john/mnt/transi**", this could be also an issue, just thinking out loud

**Comment by charterhouse-services** [comment]
thanks for the input, installed and plotting perfectly ok no issues on writing to any of the directories
running v 1.1.5 of chia - which was installed using git clone first.
fresh build OS

**Comment by ebeng** [comment]
> thanks for the input, installed and plotting perfectly ok no issues on writing to any of the directories
> running v 1.1.5 of chia - which was installed using git clone first.
> fresh build OS

You did also ofcourse do all the “aptget update/upgrades”...? 
what about all the other plotman commands like status suspend show resume?

**Comment by altendky** [comment]
This is an error that has been fixed on main.  It doesn't seem that you have installed and are running the updated version.

**Comment by Elbers60** [comment]
> This is an error that has been fixed on main. It doesn't seem that you have installed and are running the updated version.

Can anyone confirm? I don't want to go through the trouble of trying to install plotman again for nothing.
