### ISSUE TITLE
IPv6 as destination: malformed yaml

### ISSUE THREAD

**Issue by Purple-Tentacle** [ericaltendorf/plotman#506]
**Describe the bug**
I can only reach my archive server with IPv6.
When I enter the IPv6 address as-is in the configuration yaml, the : break the code.
Putting it in with [] brings a yaml malformed error.
Workaround: Put the IPv6 address in the hosts file and use the name in the config yaml.

**To Reproduce**
Put an IPv6 address in the config yaml, with or without []

**Expected behavior**
Use an IPv6 address directly in the yaml, without the workaround.

**System setup:**
 - OS: [e.g. Ubuntu, iOS, ...]
 Debian 10 on plotte and archive server.

 - Method of archiving (e.g., none, rsyncd, rsync, ...)
 rsyncd on the archive server

**Config**
<details> <summary>full configuration</summary>

```yaml
# paste your complete configuration file contents here.
```
# Default/example plotman.yaml configuration file

# Options for display and rendering
user_interface:
        # Call out to the `stty` program to determine terminal size, instead of
        # relying on what is reported by the curses library.   In some cases,
        # the curses library fails to update on SIGWINCH signals.  If the
        # `plotman interactive` curses interface does not properly adjust when
        # you resize the terminal window, you can try setting this to True. 
        use_stty_size: True

# Where to plot and log.
directories:
        # One directory in which to store all plot job logs (the STDOUT/
        # STDERR of all plot jobs).  In order to monitor progress, plotman
        # reads these logs on a regular basis, so using a fast drive is
        # recommended.
        log: /root/log

        # One or more directories to use as tmp dirs for plotting.  The
        # scheduler will use all of them and distribute jobs among them.
        # It assumes that IO is independent for each one (i.e., that each
        # one is on a different physical device).
        #
        # If multiple directories share a common prefix, reports will
        # abbreviate and show just the uniquely identifying suffix.
        tmp:
                - /root/tmp

        # Optional: Allows overriding some characteristics of certain tmp
        # directories. This contains a map of tmp directory names to
        # attributes. If a tmp directory and attribute is not listed here,
        # it uses the default attribute setting from the main configuration.
        #
        # Currently support override parameters:
        #     - tmpdir_max_jobs
        #tmp_overrides:
                # In this example, /mnt/tmp/00 is larger than the other tmp
                # dirs and it can hold more plots than the default.
                #"/mnt/tmp/00":
                        #tmpdir_max_jobs: 5

        # Optional: tmp2 directory.  If specified, will be passed to
        # chia plots create as -2.  Only one tmp2 directory is supported.
        # tmp2: /mnt/tmp/a

        # One or more directories; the scheduler will use all of them.
        # These again are presumed to be on independent physical devices,
        # so writes (plot jobs) and reads (archivals) can be scheduled
        # to minimize IO contention.
        dst:
                - /root/plots

        # Archival configuration.  Optional; if you do not wish to run the
        # archiving operation, comment this section out.
        #
        # Currently archival depends on an rsync daemon running on the remote
        # host, and that the module is configured to match the local path.
        # See code for details.
        archive:
                rsyncd_module: chia
                rsyncd_path: /mnt
                rsyncd_bwlimit: 200000  # Bandwidth limit in KB/s
                rsyncd_host: chia-farmer # IPv6 entry in /etc/hosts needed
                rsyncd_user: root
                # Optional index.  If omitted or set to 0, plotman will archive
                # to the first archive dir with free space.  If specified,
                # plotman will skip forward up to 'index' drives (if they exist).
                # This can be useful to reduce io contention on a drive on the
                # archive host if you have multiple plotters (simultaneous io
                # can still happen at the time a drive fills up.)  E.g., if you
                # have four plotters, you could set this to 0, 1, 2, and 3, on
                # the 4 machines, or 0, 1, 0, 1.
                #   index: 0

# Plotting scheduling parameters
scheduling:
        # Run a job on a particular temp dir only if the number of existing jobs
        # before tmpdir_stagger_phase_major tmpdir_stagger_phase_minor
        # is less than tmpdir_stagger_phase_limit.
        # Phase major corresponds to the plot phase, phase minor corresponds to
        # the table or table pair in sequence, phase limit corresponds to
        # the number of plots allowed before [phase major, phase minor]
        tmpdir_stagger_phase_major: 2
        tmpdir_stagger_phase_minor: 1
        # Optional: default is 1
        tmpdir_stagger_phase_limit: 1

        # Don't run more than this many jobs at a time on a single temp dir.
        tmpdir_max_jobs: 1

        # Don't run more than this many jobs at a time in total.
        global_max_jobs: 12

        # Don't run any jobs (across all temp dirs) more often than this, in minutes.
        global_stagger_m: 5

        # How often the daemon wakes to consider starting a new plot job, in seconds.
        polling_time_s: 20

# Plotting parameters.  These are pass-through parameters to chia plots create.
# See documentation at
# https://github.com/Chia-Network/chia-blockchain/wiki/CLI-Commands-Reference#create
plotting:
        k: 32
        e: False             # Use -e plotting option
        n_threads: 2         # Threads per job
        n_buckets: 128       # Number of buckets to split data into
        job_buffer: 14000     # Per job memory
        # If specified, pass through to the -f and -p options.  See CLI reference.
        farmer_pk: 1234
        pool_pk: 1234

</details>

**Additional context & screenshots**

**Comment by altendky** [comment]
Could you share the output?

**Comment by Purple-Tentacle** [comment]
If enter the IPv6 address directly (without []) into the config, the : of the address are interpreted as port number, so rsync shows this:

`(venv) root@chia05:~# rsync --bwlimit=200000 --remove-source-files -P /root/plots/filename rsync://root@1234:123:123:1234:1234:1234:1234:1234:12000/chia/plots02
ssh: Could not resolve hostname rsync: Name or service not known
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(235) [sender=3.1.3]
(venv) root@chia05:~#`

If I run the rsync ommand manuall with [], it will work (of course it cannot find the host, as the IPv6 address is fake:

`(venv) root@chia05:~# rsync --bwlimit=200000 --remove-source-files -P /root/plots/filename rsync://root@[1234:123:123:1234:1234:1234:1234:1234]:12000/chia/plots02
rsync: failed to connect to 1234:123:123:1234:1234:1234:1234:1234 (1234:123:123:1234:1234:1234:1234:1234): Connection timed out (110)
rsync error: error in socket IO (code 10) at clientserver.c(127) [sender=3.1.3]`

However, if I enter the IPv6 with [] into the config, I reaceive this wehn starttin Plotman:

`Traceback (most recent call last):
  File "/root/chia-blockchain/venv/lib/python3.7/site-packages/plotman/configuration.py", line 29, in get_validated_configs
    return schema.load(config_file)
  File "/root/chia-blockchain/venv/lib/python3.7/site-packages/marshmallow/schema.py", line 715, in load
    data, many=many, partial=partial, unknown=unknown, postprocess=True
  File "/root/chia-blockchain/venv/lib/python3.7/site-packages/marshmallow/schema.py", line 896, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'directories': {'archive': {'rsyncd_host': ['Not a valid string.']}}}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/chia-blockchain/venv/bin/plotman", line 8, in <module>
    sys.exit(main())
  File "/root/chia-blockchain/venv/lib/python3.7/site-packages/plotman/plotman.py", line 135, in main
    cfg = configuration.get_validated_configs()
  File "/root/chia-blockchain/venv/lib/python3.7/site-packages/plotman/configuration.py", line 36, in get_validated_configs
    raise ConfigurationException(f"Config file at: '{config_file_path}' is malformed") from e
plotman.configuration.ConfigurationException: Config file at: '/root/.config/plotman/plotman.yaml' is malformed`

**Comment by altendky** [comment]
How about putting it in double quotes so it is a string that includes the `[]` characters?  Square brackets are one way to make a list in yaml.
