### ISSUE TITLE
Looking for log that doesn't exist 

### ISSUE THREAD

**Issue by moechenche** [ericaltendorf/plotman#564]
Traceback (most recent call last):
  File "/home/moechenche/.local/lib/python3.8/site-packages/plotman/manager.py", line 135, in maybe_start_new_plot
    open_log_file = open(logfile, 'x')
FileNotFoundError: [Errno 2] No such file or directory: '/home/chia/chia/logs/2021-05-18T14_41_34.078026-05_00.log'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/moechenche/.local/bin/plotman", line 8, in <module>
    sys.exit(main())
  File "/home/moechenche/.local/lib/python3.8/site-packages/plotman/plotman.py", line 173, in main
    interactive.run_interactive()
  File "/home/moechenche/.local/lib/python3.8/site-packages/plotman/interactive.py", line 334, in run_interactive
    curses.wrapper(curses_main)
  File "/usr/lib/python3.8/curses/__init__.py", line 105, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/moechenche/.local/lib/python3.8/site-packages/plotman/interactive.py", line 117, in curses_main
    (started, msg) = manager.maybe_start_new_plot(
  File "/home/moechenche/.local/lib/python3.8/site-packages/plotman/manager.py", line 153, in maybe_start_new_plot
    raise Exception(message) from e
Exception: Unable to open log file.  Verify that the directory exists and has proper write permissions: '/home/chia/chia/logs/2021-05-18T14_41_34.078026-05_00.log'

That .log file doesn't exist anywhere on my computer.  Why is plotman looking for it?  How do I stop it from looking for it? I've tried changing log folder locations and even reinstalled plotman.  This Bug won't go away

**Comment by Elbers60** [comment]
it's the log file in the plotman.config file you can change it to another location, but you need make the log directory. It's not very clear in the instructions. make the log file something like 

> home/usr/plotmanlog 

then open another terminal and type 
> mkdir /home/usr/plotmanlog
> chmod 777 /home/usr/plotmanlog

I am sure there's a simpler way to make it work from your position, but this is how I made it work after struggling with the same error.

**Comment by altendky** [comment]
plotman is trying to open that log file so the plotting process can write to it.  Sorry, the error is at least misleading if not incorrectly worded.  The path shown is the file it was trying to write.  The directory the message refers to would be `/home/chia/chia/logs`.  Though, I'm guessing you perhaps meant `/home/chia/logs`?

Do not `chmod` with `777`.  There's no need for that.  Just create the directory with the same user that you will be running plotman with.

**Comment by moechenche** [comment]
Do I need to make a log file?  I made several different folders and changed the config file and that's never fixed the issue

**Comment by Elbers60** [comment]
> Just create the directory with the same user that you will be running plotman with.



> Do I need to make a log file?

Yes, and when it tells you it doesn't have permission chmod 777  🤷🏻‍♂️

**Comment by moechenche** [comment]
The problem is that there is no 2021-05-18T14_41_34.078026-05_00.log anywhere on my machine, so why plotman is looking for it is the problem.  I've tried to kill all and doesn't fix it.  I have switched to SWAR Chia because I was tired of this issue.

**Comment by Elbers60** [comment]
It makes the log. Why you need permissions to write. How hard is it to get swar running? I was going to try it until it seemed more complicated than figuring this out.

**Comment by altendky** [comment]
As I said, the full path with the file name is what is attempting to be created and written to.  It certainly will not already exist on your system.  plotman is not looking for that file.  The directory does need to exist and be writable.  And yes, the error that I made to try to help people deal with this didn't succeed in this case.  It should be reworded.

**Comment by moechenche** [comment]
> It makes the log. Why you need permissions to write. How hard is it to get swar running? I was going to try it until it seemed more complicated than figuring this out.

Swar was easy to setup. Somehow I messed plotman up. I thought everything had write access. I'll try again when I get more space.

**Comment by blundell** [comment]
I fell for this as well. You have to create the folder yourself.

Even though the error says:

> No such file or directory: '/home/chia-blockchain/plotman-logs/2021-05-27T18_38_16.805141+01_00.log'

You should read it as:

No such directory : '/home/chia/chia/plotman-logs/'

:D

**Comment by moechenche** [comment]
Problem I had is that the directory was created and I gave it permission to write to it
