### ISSUE TITLE
plotman interactive fails after few successfuly ploted plots

### ISSUE THREAD

**Issue by maxbelz** [ericaltendorf/plotman#591]
**Describe the bug**
i was running plotman interactive , everything was good, at the morning i checked my pc and saw

```python-traceback
Traceback (most recent call last):
  File "/usr/local/bin/plotman", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.8/site-packages/plotman/plotman.py", line 177, in main
    interactive.run_interactive()
  File "/home/user/.local/lib/python3.8/site-packages/plotman/interactive.py", line 334, in run_interactive
    curses.wrapper(curses_main)
  File "/usr/lib/python3.8/curses/__init__.py", line 105, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/user/.local/lib/python3.8/site-packages/plotman/interactive.py", line 261, in curses_main
    jobs_win.addstr(0, 0, reporting.status_report(jobs, n_cols, jobs_h,
  File "/home/user/.local/lib/python3.8/site-packages/plotman/reporting.py", line 95, in status_report
    row = ['...'] + ([''] * len(headings) - 1)
TypeError: unsupported operand type(s) for -: 'list' and 'int'
```

Before that error it succsessfuly created abot 20 plots...

**To Reproduce**

Steps to reproduce the behavior, e.g.:
1. Set up config with '...'  gui with plotman dev
2. Run other programs '....' no
3. Run Plotman with '....' plotman interactive

**Expected behavior**
no error

**System setup:**
 - OS: Ubuntu 20.04
 - Method of archiving NONE

**Config**
<details> <summary>32cores, 2x4tb ssd nvme (intel p4501) , 128gb ram ,4 12tb hdd</summary>

```yaml
# paste your complete configuration file contents here.
--- 
directories: 
  dst: 
    - /media/user/part3
    - /media/user/part4
    - /media/user/hdd5
    - /media/user/part6
  log: /home/user/.config/plotman/logs
  tmp: 
    - /media/user/ssd1
    - /media/user/ssd2
plotting: 
  e: false
  farmer_pk: my farmer key
  job_buffer: 3800
  k: 32
  n_buckets: 128
  n_threads: 2
  pool_pk: my pool key
scheduling: 
  global_max_jobs: 32
  global_stagger_m: 30
  polling_time_s: 50
  tmpdir_max_jobs: 16
  tmpdir_stagger_phase_limit: 14
  tmpdir_stagger_phase_major: 3
  tmpdir_stagger_phase_minor: 1
user_interface: 
  use_stty_size: true


</details>

**Additional context & screenshots**
<!-- Add any other context about the problem here, including screenshots. -->

**Comment by maxbelz** [comment]
@altendky any ideas?) accured to me second time. help please :) thank you.

**Comment by altendky** [comment]
Fixed a bit ago in https://github.com/ericaltendorf/plotman/pull/597.  You can install using the regular instructions but replace `@main` with `@development` to get the fix now.  Thanks for the report, sorry for the hassle.

**Comment by maxbelz** [comment]
@altendky wow, thanks!

**Comment by maxbelz** [comment]
problem solved
