### ISSUE TITLE
plotman crash

### ISSUE THREAD

**Issue by nashjob** [ericaltendorf/plotman#610]
plotman crash
version 0.3.1+dev

...sleeping 20 s: (True, 'Starting plot job: chia plots create -k 32 -r 2 -u 128 -b 8196 -t /swap/00 -d /plot/disk2 -f xxx -p xxx ; logging to /root/logs/plots/2021-05-21T04_11_18.667857+00_00.log')
...sleeping 20 s: (False, 'stagger (20s/60s)')
...sleeping 20 s: (False, 'stagger (41s/60s)')
...sleeping 20 s: (False, 'max jobs (50) - (61s/60s)')
...sleeping 20 s: (False, 'max jobs (50) - (81s/60s)')
...sleeping 20 s: (False, 'max jobs (50) - (102s/60s)')
...sleeping 20 s: (True, 'Starting plot job: chia plots create -k 32 -r 2 -u 128 -b 8196 -t /swap/00 -d /plot/disk1 -f xxx -p xxx; logging to /root/logs/plots/2021-05-21T04_13_20.629211+00_00.log')
...sleeping 20 s: (False, 'stagger (20s/60s)')
Traceback (most recent call last):
  File "/usr/local/bin/plotman", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/plotman/plotman.py", line 145, in main
    wait_reason = manager.maybe_start_new_plot(cfg.directories, cfg.scheduling, cfg.plotting)
  File "/usr/local/lib/python3.8/dist-packages/plotman/manager.py", line 76, in maybe_start_new_plot
    jobs = job.Job.get_running_jobs(dir_cfg.log)
  File "/usr/local/lib/python3.8/dist-packages/plotman/job.py", line 173, in get_running_jobs
    parsed_command = parse_chia_plots_create_command_line(
  File "/usr/local/lib/python3.8/dist-packages/plotman/job.py", line 48, in parse_chia_plots_create_command_line
    if 'python' in command_line[0].lower():
IndexError: list index out of range

**Comment by juligreen** [comment]
I have a similar issue

```
$ plotman interactive                                                                                                          
Traceback (most recent call last):                                                                                             
  File "/home/julius/.local/bin/plotman", line 8, in <module>                                                                  
    sys.exit(main())                                                                                                           
  File "/home/julius/.local/lib/python3.9/site-packages/plotman/plotman.py", line 173, in main                                 
    interactive.run_interactive()                                                                                                                                                                                                                                File "/home/julius/.local/lib/python3.9/site-packages/plotman/interactive.py", line 334, in run_interactive                  
    curses.wrapper(curses_main)        
  File "/usr/lib/python3.9/curses/__init__.py", line 94, in wrapper                                                            
    return func(stdscr, *args, **kwds) 
  File "/home/julius/.local/lib/python3.9/site-packages/plotman/interactive.py", line 110, in curses_main                      
    jobs = Job.get_running_jobs(cfg.directories.log, cached_jobs=jobs)                                                         
  File "/home/julius/.local/lib/python3.9/site-packages/plotman/job.py", line 173, in get_running_jobs                         
    parsed_command = parse_chia_plots_create_command_line(                                                                     
  File "/home/julius/.local/lib/python3.9/site-packages/plotman/job.py", line 48, in parse_chia_plots_create_command_line      
    if 'python' in command_line[0].lower():             
IndexError: list index out of range
```

```
$ plotman version
plotman 0.3.1+dev
```

**Comment by altendky** [comment]
Hum, there can be a command line with no elements?  That's... interesting.  I'm working on a fix but I'm curious if this happens continuously or only occasionally?

**Comment by altendky** [comment]
I'm not sure how to recreate the situation but I worked up https://github.com/ericaltendorf/plotman/pull/750 real quickly and merged it into the `development` branch.  You can either try that or wait for a release, hopefully within a few days.  Either way you will need to update your config.  When you run the new code it will give you an error including a link to instructions on the wiki.

**Comment by maxbelz** [comment]
same here . plotting with plotman for a long time, never happened.
Traceback (most recent call last):
  File "/home/user/chia-blockchain/venv/bin/plotman", line 8, in <module>
    sys.exit(main())
  File "/home/user/chia-blockchain/venv/lib/python3.8/site-packages/plotman/plotman.py", line 179, in main
    interactive.run_interactive()
  File "/home/user/chia-blockchain/venv/lib/python3.8/site-packages/plotman/interactive.py", line 335, in run_interactive
    curses.wrapper(curses_main)
  File "/usr/lib/python3.8/curses/__init__.py", line 105, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/user/chia-blockchain/venv/lib/python3.8/site-packages/plotman/interactive.py", line 114, in curses_main
    jobs = Job.get_running_jobs(cfg.directories.log)
  File "/home/user/chia-blockchain/venv/lib/python3.8/site-packages/plotman/job.py", line 177, in get_running_jobs
    parsed_command = parse_chia_plots_create_command_line(
  File "/home/user/chia-blockchain/venv/lib/python3.8/site-packages/plotman/job.py", line 48, in parse_chia_plots_create_command_line
    if 'python' in command_line[0].lower():
IndexError: list index out of range

**Comment by altendky** [comment]
Had you updated to v0.4 or v0.4.1?  They should both have the fix mentioned above.

**Comment by altendky** [comment]
@btcnash, has this issue been resolved with the more recent versions?
