### ISSUE TITLE
Plotman interactive crash on DST disconnect

### ISSUE THREAD

**Issue by Azlec** [ericaltendorf/plotman#685]
I've been plotting to external USB drives as DST. One of the USB drives is faulty and randomly restarts. Every time the drive restarts, Linux loses its mount and plotman interactive crashes. Ideally, plotman would continue running and plot towards all other DST drives (9 others in my case).

Similarly, plotman fails to start if one of the DST drives is not available/mounted.

Full error message (mnt/hdd10 as faulty USB drive): 
`Traceback (most recent call last):
  File "/home/chiaplotter/chia-blockchain/venv/bin/plotman", line 8, in <module>
    sys.exit(main())
  File "/home/chiaplotter/chia-blockchain/venv/lib/python3.8/site-packages/plotman/plotman.py", line 173, in main
    interactive.run_interactive()
  File "/home/chiaplotter/chia-blockchain/venv/lib/python3.8/site-packages/plotman/interactive.py", line 334, in run_interactive
    curses.wrapper(curses_main)
  File "/usr/lib/python3.8/curses/__init__.py", line 105, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/chiaplotter/chia-blockchain/venv/lib/python3.8/site-packages/plotman/interactive.py", line 180, in curses_main
    dst_report = reporting.dst_dir_report(
  File "/home/chiaplotter/chia-blockchain/venv/lib/python3.8/site-packages/plotman/reporting.py", line 162, in dst_dir_report
    dir_plots = plot_util.list_k32_plots(d)
  File "/home/chiaplotter/chia-blockchain/venv/lib/python3.8/site-packages/plotman/plot_util.py", line 51, in list_k32_plots
    for plot in os.listdir(d):
OSError: [Errno 5] Input/output error: '/mnt/hdd10'`

*Logically.. I'm sending the drive back, but still think it might be worth fixing to prevent plot process interruptions.

**Comment by leonidcan** [comment]
I also experience similar situation. Could we have a fix please?

**Comment by leonidcan** [comment]
Also missing temp folder would crash plotman. I think it should just give a warning
