### ISSUE TITLE
Error when start plotman

### ISSUE THREAD

**Issue by stou80** [ericaltendorf/plotman#693]
Hello

I have the following error message when I want to launch plotman.
Do you know what happened?

`(venv)` root@frhb61160ds:/chia-blockchain# plotman plot
Traceback (most recent call last):
  File "/chia-blockchain/venv/bin/plotman", line 8, in <module>
    sys.exit(main())
  File "/chia-blockchain/venv/lib/python3.8/site-packages/plotman/plotman.py", line 137, in main
    cfg = configuration.get_validated_configs(config_text, config_path)
  File "/chia-blockchain/venv/lib/python3.8/site-packages/plotman/configuration.py", line 37, in get_validated_configs
    config_objects = yaml.load(config_text, Loader=yaml.SafeLoader)
  File "/chia-blockchain/venv/lib/python3.8/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/chia-blockchain/venv/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/chia-blockchain/venv/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/chia-blockchain/venv/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/chia-blockchain/venv/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/chia-blockchain/venv/lib/python3.8/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/chia-blockchain/venv/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/chia-blockchain/venv/lib/python3.8/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/chia-blockchain/venv/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/chia-blockchain/venv/lib/python3.8/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
  in "<unicode string>", line 114, column 9:
            k: 32
            ^
expected <block end>, but found '<block mapping start>'
  in "<unicode string>", line 120, column `12:`

Thanks for your help

Stéphane

**Comment by sourcenux** [comment]
I suspect that your config.yaml is broken.

**Comment by toboladao** [comment]
Any idea how to fix this?

**Comment by sourcenux** [comment]
Please post your config.yaml

**Comment by jeus1609** [comment]
remove config.yaml
and then "plotman generate"
