### ISSUE TITLE
Occasionally runs into UnicodeDecodeError, chia crashed

### ISSUE THREAD

**Issue by Gaukas** [ericaltendorf/plotman#710]
**Describe the bug**

<details> <summary>log</summary>

```python-traceback
Traceback (most recent call last):
  File "/home/ubuntu/chia-blockchain/venv/bin/plotman", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/chia-blockchain/venv/lib/python3.8/site-packages/plotman/plotman.py", line 145, in main
    wait_reason = manager.maybe_start_new_plot(cfg.directories, cfg.scheduling, cfg.plotting)
  File "/home/ubuntu/chia-blockchain/venv/lib/python3.8/site-packages/plotman/manager.py", line 76, in maybe_start_new_plot    jobs = job.Job.get_running_jobs(dir_cfg.log)
  File "/home/ubuntu/chia-blockchain/venv/lib/python3.8/site-packages/plotman/job.py", line 154, in get_running_jobs
    job = Job(
  File "/home/ubuntu/chia-blockchain/venv/lib/python3.8/site-packages/plotman/job.py", line 223, in __init__
    self.init_from_logfile()
  File "/home/ubuntu/chia-blockchain/venv/lib/python3.8/site-packages/plotman/job.py", line 267, in init_from_logfile
    self.update_from_logfile()
  File "/home/ubuntu/chia-blockchain/venv/lib/python3.8/site-packages/plotman/job.py", line 270, in update_from_logfile
    self.set_phase_from_logfile()
  File "/home/ubuntu/chia-blockchain/venv/lib/python3.8/site-packages/plotman/job.py", line 283, in set_phase_from_logfile
    for line in f:
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa8 in position 468: invalid start byte
```

</details>

The relevant `chia` process crashed (during phase 3) as well. Not sure if `chia` crashed before `plotman` or the other way. Note: the `chiapos` being used wasn't a genuine version which might crash. 

**To Reproduce**

No efficient way was found to reproduce, happened only 3 times in 2 days among 7 machines.

**Expected behavior**

`plotman` is not expected to be more robust when handling such problems. (e.g. `chia` process killed unexpectedly, can't decode log, etc)

**System setup:**
 - OS: Ubuntu 20.04

**Config**
<details> <summary>full configuration</summary>

```yaml
user_interface:
        use_stty_size: True

directories:
        log: /chia-logs/
        tmp:
                - /data/plots
        dst:
                - /data/plots

# Plotting scheduling parameters
scheduling:
        tmpdir_stagger_phase_major: 2
        tmpdir_stagger_phase_minor: 1
        # Optional: default is 1
        tmpdir_stagger_phase_limit: 1

        # Don't run more than this many jobs at a time on a single temp dir.
        tmpdir_max_jobs: 3

        # Don't run more than this many jobs at a time in total.
        global_max_jobs: 3

        # Don't run any jobs (across all temp dirs) more often than this, in minutes.
        global_stagger_m: 70

        # How often the daemon wakes to consider starting a new plot job, in seconds.
        polling_time_s: 600

plotting:
        k: 32
        e: False             # Use -e plotting option
        n_threads: 8         # Threads per job
        n_buckets: 128       # Number of buckets to split data into
        job_buffer: 4096     # Per job memory
        # If specified, pass through to the -f and -p options.  See CLI reference.
        farmer_pk: [REDACTED] 
        pool_pk: [REDACTED]
```

</details>

**Comment by Gaukas** [comment]
Possibly just don't crash it but ignore it when the log is unreadable 😄

**Comment by altendky** [comment]
Yeah, plotman not crashing out would be a good thing.  I did a simple thing in https://github.com/ericaltendorf/plotman/pull/748.  I'll mull it over and see if I think it's actually good.
