### ISSUE TITLE
missing curses/ readline

### ISSUE THREAD

**Issue by Hardcore-fs** [ericaltendorf/plotman#732]
this is on linux centos7,
 it installed fine on osx not a problem.

Traceback (most recent call last):
  File "/home/chia/myvenv/bin/plotman", line 5, in <module>
    from plotman.plotman import main
  File "/home/chia/myvenv/lib/python3.9/site-packages/plotman/plotman.py", line 10, in <module>
    from plotman import analyzer, archive, configuration, interactive, manager, plot_util, reporting
  File "/home/chia/myvenv/lib/python3.9/site-packages/plotman/interactive.py", line 1, in <module>
    import curses
  File "/usr/local/lib/python3.9/curses/__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'

**Comment by Hardcore-fs** [comment]
never mind garbage install of python...
seems as if there are system libraries are not installed before python 3.9 is compiled
then there are all sorts of places python 3.9 gets broken silently...

**Comment by altendky** [comment]
Yep.  The [pyenv wiki](https://github.com/ericaltendorf/plotman/wiki/Archiving) has a nice list of dependencies to install before compiling.  Useful even if you aren't using pyenv.
