### ISSUE TITLE
Exception: Failed to initialize curses windows, try a larger terminal window.

### ISSUE THREAD

**Issue by dendisuhubdy** [ericaltendorf/plotman#738]
```python-traceback
Traceback (most recent call last):
  File "/home/chia/chia-blockchain/venv/lib/python3.8/site-packages/plotman-0.3.1-py3.8.egg/plotman/interactive.py", line 217, in curses_main
_curses.error: curses function returned NULL

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chia/chia-blockchain/venv/bin/plotman", line 11, in <module>
    load_entry_point('plotman==0.3.1', 'console_scripts', 'plotman')()
  File "/home/chia/chia-blockchain/venv/lib/python3.8/site-packages/plotman-0.3.1-py3.8.egg/plotman/plotman.py", line 173, in main
  File "/home/chia/chia-blockchain/venv/lib/python3.8/site-packages/plotman-0.3.1-py3.8.egg/plotman/interactive.py", line 334, in run_interactive
  File "/usr/lib/python3.8/curses/__init__.py", line 105, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/chia/chia-blockchain/venv/lib/python3.8/site-packages/plotman-0.3.1-py3.8.egg/plotman/interactive.py", line 221, in curses_main
Exception: Failed to initialize curses windows, try a larger terminal window.
```

**Comment by altendky** [comment]
Did you try a larger terminal window?  Or a smaller font?  But yes, this is a problem.  I started working on switching away from curses so that's my planned 'solution'.  Sorry for the trouble.

**Comment by dendisuhubdy** [comment]
yes I did and it worked but it's weird. I initialized plotman on a very large screen but when I moved to a macbook pro where I ssh-ed and then tmux attached the screen, it doesn't because it was initialzied on the previously large screen I had.

**Comment by dendisuhubdy** [comment]
smaller fonts worked for me
