### ISSUE TITLE
PsUtil access denied in MacOS

### ISSUE THREAD

**Issue by Handri-Kosada** [ericaltendorf/plotman#91]
I manage to run the development branch in Ubuntu

But when I try in MacOs I got this error below. 
It  seems we need to ask Access Permission in MacOs first?

Thanks

```python-traceback
Traceback (most recent call last):
  File "/Users/kosada/chia/chia/venv/bin/plotman", line 8, in <module>
    sys.exit(main())
  File "/Users/kosada/chia/chia/venv/lib/python3.8/site-packages/plotman/plotman.py", line 127, in main
    jobs = Job.get_running_jobs(dir_cfg['log'])
  File "/Users/kosada/chia/chia/venv/lib/python3.8/site-packages/plotman/job.py", line 84, in get_running_jobs
    if is_plotting_cmdline(proc.cmdline()):
  File "/Users/kosada/chia/chia/venv/lib/python3.8/site-packages/psutil/init.py", line 677, in cmdline
    return self._proc.cmdline()
  File "/Users/kosada/chia/chia/venv/lib/python3.8/site-packages/psutil/_psosx.py", line 351, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=1)
```

**Comment by altendky** [comment]
If you want you can try the branch `altendky-patch-6`.

**Comment by Handri-Kosada** [comment]
Tried this under activate :
pip install git+https://github.com/ericaltendorf/plotman@altendky-patch-6

Then run : plotman interactive
still shows the same error

**Comment by Handri-Kosada** [comment]
(venv) ➜  chia sed -n '80,85p;86q' /Users/kosada/chia/chia/venv/lib/python3.8/site-packages/plotman/job.py
        for proc in psutil.process_iter(['pid', 'cmdline']):
            # Ignore processes which most likely have terminated between the time of
            # iteration and data access.
            with contextlib.suppress(psutil.NoSuchProcess):
                if is_plotting_cmdline(proc.cmdline()):
                    if proc.pid in cached_jobs_by_pid.keys():

**Comment by altendky** [comment]
Fixed I believe.  We're debugging the next issue on Keybase.

https://github.com/ericaltendorf/plotman/issues/38
