### ISSUE TITLE
pip install does not work on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by hostingnuggets** [ericaltendorf/plotman#971]
**Describe the bug**
pip install does not work on Ubuntu 22.04 LTS

**To Reproduce**

Steps to reproduce the behavior, e.g.:
1. Install Ubuntu 22.04 LTS Server
2. Run: `pip install --force-reinstall git+https://github.com/ericaltendorf/plotman@main` 

**Expected behavior**
Should install plotman successfully.

**System setup:**
 - OS: Ubuntu 22.04 LTS Server

**Config**
None yet

</details>

**Additional context & screenshots**
```yaml
$ pip install --force-reinstall git+https://github.com/ericaltendorf/plotman@main
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/ericaltendorf/plotman@main
  Cloning https://github.com/ericaltendorf/plotman (to revision main) to /tmp/pip-req-build-jt3m0is9
  Running command git clone --filter=blob:none --quiet https://github.com/ericaltendorf/plotman /tmp/pip-req-build-jt3m0is9
  Resolved https://github.com/ericaltendorf/plotman to commit 1b7dfba139ed03d3c32a2f04f6011e03bfb1f442
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting desert==2020.11.18
  Downloading desert-2020.11.18-py3-none-any.whl (9.5 kB)
Collecting packaging~=20.9
  Downloading packaging-20.9-py2.py3-none-any.whl (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.9/40.9 KB 1.4 MB/s eta 0:00:00
Collecting marshmallow~=3.12
  Using cached marshmallow-3.20.1-py3-none-any.whl (49 kB)
Collecting pyyaml~=5.4
  Using cached PyYAML-5.4.1.tar.gz (175 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [43 lines of output]
      running egg_info
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 271, in <module>
          setup(
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 299, in run
          self.find_sources()
        File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 306, in find_sources
          mm.run()
        File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 541, in run
          self.add_defaults()
        File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 578, in add_defaults
          sdist.add_defaults(self)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/command/sdist.py", line 228, in add_defaults
          self._add_defaults_ext()
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/command/sdist.py", line 312, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
        File "setup.py", line 201, in get_source_files
          self.cython_sources(ext.sources, ext)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 103, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by Flint4** [comment]
Same here using Py 3.10.12.

Got it installed using 
`pip install --force-reinstall packaging==21.0 typing-extensions==4.0.1 --ignore-installed pyyaml git+https://github.com/ericaltendorf/plotman@development`
as suggested in https://github.com/ericaltendorf/plotman/issues/952
